### ISSUE TITLE
Two files missing to make it work

### ISSUE THREAD

**Issue by l4nj1n9** [beastybeast/pcrypt#3]
It seems that at least two files are missing to make the stuff work for me: `sha256.inc.php` and `captcha.inc.php`. You do not talk about them in the "Dependency" section of the `README` file. Where can I get those ?

**Comment by beastybeast** [comment]
Sorry this project have not been updated for a while as we moved back to SVN and as far as I know github does not support that. I will update it when we are ready with the next version of the complete system (this is just the back bone).
Really a lot have changed. E.g. almost every file and lib.
If you really need it now I can send it to you?
I think I also have the old files if you prefer them?

**Comment by l4nj1n9** [comment]
My mail is available on [my profile](https://github.com/taophp).
Do you planned to published the source to the public ? If yes, please, send them to me and tell me where and when you plan to publish.
The fact is that I planned to release a paper for the French version of _Linux Magazine_ (my boss expects it for Monday!) but I will avoid it if the sources are closed in any way.
In the new version, is there an usable HTML front-end? I _may_ write my paper if not, but later as it changes the point of view. Originally, my paper was end-user oriented, with just a part dedicated to self-hosting Passwordcrypt for advanced ones, but if the front-end is missing, I must switch to a developer point of view, which will take longer to write.

BTW: have you seen [this magazine](https://boutique.ed-diamond.com/gnulinux-magazine/926-gnulinux-magazine-191.html) (French only, sorry) ? I published a paper on your implementation of SRP and how to use it, page 72.

**Comment by beastybeast** [comment]
Yes sorry my French is very bad even if I am there ones a year

The core lib will be release to the public - I do not know when.

You can find a  usable HTML front-end.

The old version (github) https://pcrypt.org
Development version https://pcrypt.org/dev

I currently use this SRP version: https://bitbucket.org/beastybeast/thinbus-php-demo2/overview

So I think there is no need for me to send you the old files ;-)

**Comment by beastybeast** [comment]
Working demo here: http://pcrypt.dk/dev/rod/demo/

**Comment by l4nj1n9** [comment]
> I currently use this SRP version

I know: it's the one I wrote about in the mag. We had [some discussions](https://bitbucket.org/beastybeast/thinbus-php-demo2/issues/1/a-bit-too-slow) about it at the time I was writing my paper.

**Comment by l4nj1n9** [comment]
> You can find a usable HTML front-end.

Do you mean that you will publish one or that I may find one in the wild ?

**Comment by beastybeast** [comment]
This link use it: https://pcrypt.org/dev during login

But I do not plan to release the password site in total as Open Source just the core libs (encryption, srp etc.)

**Comment by l4nj1n9** [comment]
> The core lib will be release to the public - I do not know when.

Please, let me know when you know when you release the new site and the sources to the public. I think I will delay my paper to this time.

**Comment by beastybeast** [comment]
I do not think it will take that long as the pcrypt site is almost complete.

**Comment by l4nj1n9** [comment]
> But I do not plan to release the password site in total as Open Source just the core libs (encryption, srp etc.)

Well, I will write a coder oriented paper. If you mind my point of view, it should be great to offer an self-hosted solution for those who want it. There is good reasons for that and I think you can imagine them, even if they are not ours.

> I do not think it will take that long as the pcrypt site is almost complete.

Cool!

**Comment by l4nj1n9** [comment]
BTW: https://pcrypt.org/phpBB/ : Fatal: ./cache/ is NOT writable.

**Comment by beastybeast** [comment]
Use: https://pcrypt.org/dev/phpBB/

**Comment by beastybeast** [comment]
My plan is to make a simpel shell around the core libs to show what can be done with it -also posted online.

BTW: Can you some how send me the article as I like to give it to my brother that has been living in France for the last 20 years.

**Comment by l4nj1n9** [comment]
> Can you some how send me the article

On your mail, I can send you a scan of the magazine as I get it on paper. I do not have the "official" PDF, but I can send you a not-so-pretty PDF version of my working file, as you like.

By the way, if your brother is currently in France, he may buy the whole magazine, it's the current month issue, so he can find it in store. Or [inline](https://boutique.ed-diamond.com/gnulinux-magazine/926-gnulinux-magazine-191.html) at any time.
